export const lottery_tickets = [
    {
        id: 1,
        name: "Ticket 1",
        expires_at: "2023-12-31",
        prize_pool: "100",
        price: 10,
        manager_id: 1,
        subscribers: [1],
    },
    {
        id: 2,
        name: "Ticket 2",
        expires_at: "2023-12-31",
        prize_pool: "150",
        price: 15,
        manager_id: 1,
        subscribers: [1, 2],
    },
    {
        id: 3,
        name: "Ticket 3",
        expires_at: "2023-12-31",
        prize_pool: "200",
        price: 20,
        manager_id: 1,
        subscribers: [2],
    },
    {
        id: 4,
        name: "Ticket 4",
        expires_at: "2023-12-31",
        prize_pool: "120",
        price: 12,
        manager_id: 2,
        subscribers: [2, 3],
    },
    {
        id: 5,
        name: "Ticket 5",
        expires_at: "2023-12-31",
        prize_pool: "180",
        price: 18,
        manager_id: 2,
        subscribers: [1, 2, 3],
    },
    {
        id: 6,
        name: "Ticket 6",
        expires_at: "2023-12-31",
        prize_pool: "250",
        price: 25,
        manager_id: 2,
        subscribers: [1, 3],
    },
    {
        id: 7,
        name: "Ticket 7",
        expires_at: "2023-12-31",
        prize_pool: "90",
        price: 9,
        manager_id: 3,
        subscribers: [1],
    },
    {
        id: 8,
        name: "Ticket 8",
        expires_at: "2023-12-31",
        prize_pool: "160",
        price: 16,
        manager_id: 3,
        subscribers: [2],
    },
    {
        id: 9,
        name: "Ticket 9",
        expires_at: "2023-12-31",
        prize_pool: "220",
        price: 22,
        manager_id: 3,
        subscribers: [3],
    },
    {
        id: 10,
        name: "Ticket 10",
        expires_at: "2023-12-31",
        prize_pool: "130",
        price: 13,
        manager_id: 3,
        subscribers: [1, 2, 3],
    },
];
